---
title: "Judy+Rosie+ZZ_Project"
author: "Judy Zhu, Ruoxi Wu, Zhaoxin Zhang"
date: "2024-11-11"
output: html_document
---
# Install and load required packages
```{r setup, include=FALSE}
install.packages("httr")
install.packages("jsonlite")
library(httr)
library(jsonlite)
library(tidyverse)
library(dplyr)
library(lubridate)
library(readr)
```
# Define the base URL and parameters for OpenMeteo API

```{r the base URL and parameters }
base_url <- "https://archive-api.open-meteo.com/v1/era5" # Use archive API for historical data
parameters <- list(
  latitude = 31.9686,        # Latitude for Texas
  longitude = -99.9018,      # Longitude for Texas
  start_date = "2016-01-01", # Start date
  end_date = "2023-12-31",   # End date
  daily = "temperature_2m_max,temperature_2m_min",# Daily temperature data
  timezone = "America/Chicago" # Specify the timezone
)
```


```{r pressure, echo=FALSE}
# Make the API request
response <- GET(base_url, query = parameters)
```

```{r include=FALSE}
# Check if the request was successful
if (status_code(response) == 200) {
# Parse the JSON response
weather_data_Texas <- fromJSON(content(response, "text"))
print(weather_data_Texas)
} else {
  print("Failed to fetch data")
}
```

```{r}

# Assuming weather_data_Texas contains the JSON data
if (!is.null(weather_data_Texas$daily)) {
  
# Extract dates, max temperatures, and min temperatures
dates <- weather_data_Texas$daily$time
temp_max <- weather_data_Texas$daily$temperature_2m_max
temp_min <- weather_data_Texas$daily$temperature_2m_min
  
# Combine into a data frame
weather_Texas_df <- data.frame(
  Date = as.Date(dates),  # Convert dates to Date format
  Temperature_Max = temp_max,
  Temperature_Min = temp_min
  )
  
# Display the data frame
print(weather_Texas_df)
} else {print("No daily weather data available")
}

```
```{r}
library(here)
here()
install.packages("readxl")
library("readxl")
```


```{r}
#Load 2016-2021 hourly Energy Load data
Energy_2016 <- read_excel(here('Data/Raw/EnergyLoad_ercot/native_Load_2016.xlsx'))
Energy_2017 <- read_excel(here('Data/Raw/EnergyLoad_ercot/native_Load_2017.xlsx'))
Energy_2018 <- read_excel(here('Data/Raw/EnergyLoad_ercot/Native_Load_2018.xlsx'))
Energy_2019 <- read_excel(here('Data/Raw/EnergyLoad_ercot/Native_Load_2019.xlsx'))
Energy_2020 <- read_excel(here('Data/Raw/EnergyLoad_ercot/Native_Load_2020.xlsx'))
Energy_2021 <- read_excel(here('Data/Raw/EnergyLoad_ercot/Native_Load_2021.xlsx'))
Energy_2022 <- read_excel(here('Data/Raw/EnergyLoad_ercot/Native_Load_2022.xlsx'))
Energy_2023 <- read_excel(here('Data/Raw/EnergyLoad_ercot/Native_Load_2023.xlsx'))
```


```{r}
# Combine the 2016-2023 energy data, and wrangle to only date and total energy load "ERCOT"
#Change each data's variable name to ensure consistency
Energy_2017 <- rename(Energy_2017, Hour_End = "Hour Ending")
Energy_2018 <- rename(Energy_2018, Hour_End = "HourEnding")
Energy_2019 <- rename(Energy_2019, Hour_End = "HourEnding")
Energy_2020 <- rename(Energy_2020, Hour_End = "HourEnding")
Energy_2021 <- rename(Energy_2021, Hour_End = "Hour Ending")
Energy_2022 <- rename(Energy_2022, Hour_End = "Hour Ending")
Energy_2023 <- rename(Energy_2023, Hour_End = "Hour Ending")

#Check the class of Energy_2016 Hour_End
class(Energy_2016$Hour_End)

#Convert Energy_2016 Hour_End to date 
Energy_2016 <- Energy_2016 %>%
  mutate(Date = as.Date(Hour_End))

#Check the class of Energy_2017 Hour_End
class(Energy_2017$Hour_End)

# Convert character Hour_End to POSIXct format (date-time) first
Energy_2017 <- Energy_2017 %>%
  mutate(Hour_End = mdy_hm(Hour_End)) 

#Then convert Energy_2017 Hour_End to date 
Energy_2017 <- Energy_2017 %>%
  mutate(Date = as.Date(Hour_End))

#Check the class of Energy_2018 Hour_End
class(Energy_2018$Hour_End)

# Convert character Hour_End to POSIXct format (date-time)
Energy_2018 <- Energy_2018 %>%
  mutate(Hour_End = mdy_hm(Hour_End))

#Then convert Energy_2018 Hour_End to date 
Energy_2018 <- Energy_2018 %>%
  mutate(Date = as.Date(Hour_End))

#Check the class of Energy_2019 Hour_End
class(Energy_2019$Hour_End)

# Convert character Hour_End to POSIXct format (date-time)
Energy_2019 <- Energy_2019 %>%
  mutate(Hour_End = mdy_hm(Hour_End))

#Then convert Energy_2019 Hour_End to date 
Energy_2019 <- Energy_2019 %>%
  mutate(Date = as.Date(Hour_End))

#Check the class of Energy_2020 Hour_End
class(Energy_2020$Hour_End)

# Convert character Hour_End to POSIXct format (date-time)
Energy_2020 <- Energy_2020 %>%
  mutate(Hour_End = mdy_hm(Hour_End))

#Then convert Energy_2020 Hour_End to date 
Energy_2020 <- Energy_2020 %>%
  mutate(Date = as.Date(Hour_End))

#Check the class of Energy_2021 Hour_End
class(Energy_2021$Hour_End)

# Convert character Hour_End to POSIXct format (date-time)
Energy_2021 <- Energy_2021 %>%
  mutate(Hour_End = mdy_hm(Hour_End))

#Then convert Energy_2021 Hour_End to date 
Energy_2021 <- Energy_2021 %>%
  mutate(Date = as.Date(Hour_End))

#Check the class of Energy_2022 Hour_End
class(Energy_2022$Hour_End)

# Convert character Hour_End to POSIXct format (date-time)
Energy_2022 <- Energy_2022 %>%
  mutate(Hour_End = mdy_hm(Hour_End))

#Then convert Energy_2022 Hour_End to date 
Energy_2022 <- Energy_2022 %>%
  mutate(Date = as.Date(Hour_End))

#Check the class of Energy_2023 Hour_End
class(Energy_2023$Hour_End)

# Convert character Hour_End to POSIXct format (date-time)
Energy_2023 <- Energy_2023 %>%
  mutate(Hour_End = mdy_hm(Hour_End))

#Then convert Energy_2023 Hour_End to date 
Energy_2023 <- Energy_2023 %>%
  mutate(Date = as.Date(Hour_End))

#Keep only the Data and ERCOT
Energy_2016 <- Energy_2016 %>%
  select(Date, ERCOT)
Energy_2017 <- Energy_2017 %>%
  select(Date, ERCOT)
Energy_2018 <- Energy_2018 %>%
  select(Date, ERCOT)
Energy_2019 <- Energy_2019 %>%
  select(Date, ERCOT)
Energy_2020 <- Energy_2020 %>%
  select(Date, ERCOT)
Energy_2021 <- Energy_2021 %>%
  select(Date, ERCOT)
Energy_2022 <- Energy_2022 %>%
  select(Date, ERCOT)
Energy_2023 <- Energy_2023 %>%
  select(Date, ERCOT)

#Combine all the dataset into one
EnergyLoad_Daily <- bind_rows(
  list(
    Energy_2016 = Energy_2016,
    Energy_2017 = Energy_2017,
    Energy_2018 = Energy_2018,
    Energy_2019 = Energy_2019,
    Energy_2020 = Energy_2020,
    Energy_2021 = Energy_2021,
    Energy_2022 = Energy_2022,
    Energy_2023 = Energy_2023
  ),
  .id = "Data"
)

EnergyLoad_Daily <- EnergyLoad_Daily %>%
  select(Date, ERCOT)

sum(is.na(EnergyLoad_Daily)) #See how many NAs 

# Remove rows with NA
EnergyLoad_Daily <- EnergyLoad_Daily %>% filter(!is.na(Date))  

EnergyLoad_Daily <- EnergyLoad_Daily %>% filter(!is.na(ERCOT))

sum(is.na(EnergyLoad_Daily)) #No NAs

#Turn the hourly data to daily data
EnergyLoad_Daily <- EnergyLoad_Daily %>%
  group_by(Date) %>%
  summarise(Daily_ERCOT = sum(ERCOT, na.rm = TRUE))

#Rename the columns
colnames(EnergyLoad_Daily) <- c("Date", "ERCOT(MW)")

```

```{r}
#Import Electricity Price Data
ElectricityPrice_Monthly <- read.csv("Data/Raw/EnergyPrice/SeriesExport-11-20-2024-10-13-55.csv",
                                     stringsAsFactors =TRUE)

#Select data from 2016-01 to 2023-12
ElectricityPrice_Monthly <- ElectricityPrice_Monthly %>%
  filter(row_number() >= 15) %>%
  filter(row_number() <= 96) %>%
  select(Series.Key, ELEC.PRICE.TX.ALL.M)

#Rename the variables
colnames(ElectricityPrice_Monthly) <- c("Date", "Price(cent/KWh)")

#Convert to Date format
ElectricityPrice_Monthly <- ElectricityPrice_Monthly %>%
  mutate(Date = ym(Date))

#Convert to numeric format
ElectricityPrice_Monthly$`Price(cent/KWh)` <- as.numeric(as.character(ElectricityPrice_Monthly$`Price(cent/KWh)`))

#Rearrange the Date
ElectricityPrice_Monthly <- ElectricityPrice_Monthly %>%
  arrange(Date)
```

```{r}
#Export processed data into Processed folder
write.csv(EnergyLoad_Daily, row.names = FALSE, 
          file ="./Data/Processed/EnergyLoad_Daily.csv") 
write.csv(ElectricityPrice_Monthly, row.names = FALSE, 
          file ="./Data/Processed/ElectricityPrice_Monthly.csv") 
write.csv(weather_Texas_df, row.names = FALSE, 
          file ="./Data/Processed/Temperature_MaxMin_Daily.csv") 

```

