\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory

# Load your packages

# Set your ggplot theme

# Load your datasets

```


# Rationale and Research Questions



\newpage

# 3 Dataset Information
The data used for this analysis is from different sources. Historical records of temperature can be found in the archive API https://archive-api.open-meteo.com/v1/era5. Given the information on Texas's latitude and longitude and the start and end dates from January 2016 to December 2023, the API archive could provide data on daily temperature in Texas from 2016 to 2023. The API gave the maximum and minimum temperatures in Texas from 2016 to 2023 in degrees Celsius. The Electric Reliability Council of Texas (ERCOT) gave hourly energy load data in Texas, from year 2016 to 2023, in MW. The U.S. Energy Information Administration (EIA) contained monthly average electricity price data from 2001 to 2024, and the unit was cent/kWh. The data for daily electricity prices was unavailable. All of the data from the three sources used in this analysis had a date column, which could ensure the time series analysis's viability. The data had continuous data on daily temperature, hourly load, and monthly price, which would be used for both time series and linear model analysis. The data and sources are listed below (Table 3.1).

Table 3.1: Table summarizing the data sources
  
Data Sources
-------------:|:-------------
API  | Texas Daily Max and Min Temperature
ERCOT | Texas Hourly Energy Load
EIA | Texas Monthly Electricity Price

\newpage

# 4 Data Wrangling
The API data contained three columns: date, daily max temperature, and daily min temperature. The date column was in "character" format and thus needed to be converted to "date" format using the as.Date() code for the following analysis. The raw ERCOT data contained hourly energy load data, but the analysis needed to be done at the daily level of energy load. Thus, the ERCOT's data was aggregated and converted from hourly data to daily data. The ERCOT data had 10 columns: Date and Hourly Energy Load in MW via 9 different regions or standards. The analysis chose to use the ERCOT energy load, selecting only two columns from the data: Date and ERCOT. The official website did not provide aggregated data from 2016 to 2023. Instead, it provided each year's data. The data from 2016 to 2023 was aggregated in one data called "EnergyLoad_Daily." This data would be used for analysis and visualization. The daily data w a s
was then aggregated into monthly data for later analysis. The EIA's data gave 8 variables, including the date and electricity price via different end-use. This analysis would use the average electricity price for all sectors, so only two columns were selected: Date and Average Electricity Price among All Sectors. The data included information from 2001 to 2024, while the analysis only needed data from 2016 to 2023. Therefore, a code filtered data from row 15 to row 96, selecting date only from 2016 to 2023. 

All the data's Date columns were converted to "date" format, and all other columns were converted to "numeric" format to make the latter analyses available. The raw data was uploaded to the "Data/Raw" file, and the processed datasets: monthly electricity price, daily energy load, monthly energy load, and daily temperature, were uploaded to the "Data/Processed" file in CSV format for the visualization, linear model analysis, and time series analysis. 

\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
